export const SET_TOKEN = 'SET_TOKEN'

export const SET_TIMESTAMP = 'SET_TIMESTAMP'

export const SET_UID = 'SET_UID'

export const SET_USER = 'SET_USER'

export const SET_PHILOSOPHERLIST = 'SET_PHILOSOPHERLIST'

export const SET_PHILOSOPHER = 'SET_PHILOSOPHER'

export const SET_LISTREFRESH = 'SET_LISTREFRESH'
